import h5py

from ..pipeline import Pipeline


class QLSIPipeline(Pipeline):
    def convert(self):
        """Convert QLSI tif data generated by Micro-Manager in SPIM setup"""


    def get_raw_data_list(self):
        datalist = []
        for pp in sorted(self.path_raw.rglob("*.tif")):
            pass