import h5py

from ..core import Converter


class QLSIConverter(Converter):
    def convert(self):
        """Convert QLSI tif data generated by Micro-Manager by Ray"""


    def get_raw_data_list(self):
        datalist = []
        for pp in sorted(self.path_raw.rglob("*.tif")):
