from ..recipe import Recipe


class QLSIRecipe(Recipe):
    def convert(self):
        """Convert QLSI tif data generated by Micro-Manager in SPIM setup"""

    def get_raw_data_list(self):
        datalist = []
        for pp in sorted(self.path_raw.rglob("*.tif")):
            # TODO
            pass
        return datalist
